### ISSUE TITLE
Local date used instead of UTC in module

### ISSUE THREAD

**Issue by theiostream** [pagarme/node-boleto#17]
Many internal components of the module use Date arithmetic initializing it in the local timezone instead of in UTC, which generates complications across different timezones and for testing the module.

**Comment by mccraveiro** [comment]
@lucianopf @Thor99 Can we close this issue? I think it was solved on [this commit](https://github.com/pagarme/node-boleto/commit/4f326041d6ff95b4d1cd7f1a6f754cca58f0ee33).

**Comment by lucianopf** [comment]
Nice catch @mccraveiro !!
