### ISSUE TITLE
Support Itaú Bank

### ISSUE THREAD

**Issue by rturk** [pagarme/node-boleto#19]
Create schema for Itau Bank

**Comment by theiostream** [comment]
Tem um PR (#4) que adiciona integração Itaú a esse projeto. Ele ficou ignorado por um bom tempo mas dei uma resposta pedindo algumas alterações para que ele seja mergeado.

O cara do PR tem um fork que suporta integração Itaú, embora não tenha algumas das coisas novas desse repositório (e.g. segurança maior dos boletos, testes).

Vou fechar esse issue. Se você quiser discutir mais sobre essa integração comente naquele PR.
