### ISSUE TITLE
print in pdf

### ISSUE THREAD

**Issue by elisangelacarla** [pagarme/node-boleto#21]
Good afternoon, when printing the ticket in pdf printer the barcode loses its quality, is there any way or method implemented to print in pdf?

**Comment by mccraveiro** [comment]
@elisangelacarla thanks for the feedback :)

Which browser/version are you using?
Our tests have shown that this is happening only on Chrome. 
We'll work on a solution but it's not a priority right now.

Feel free to send suggestions or to open a pull request ❤️
