### ISSUE TITLE
Boleto Registrado

### ISSUE THREAD

**Issue by GlauberF** [pagarme/node-boleto#25]
Através da lib hoje, consigo gerar boleto registrado ?

**Comment by otaviopace** [comment]
A bibiloteca somente gera um HTML com as informações de um boleto. Para registrar um boleto é necessário ter uma carteira em um banco que registra boletos e então enviar as infromações necessárias a ele. O [superbowleto](https://github.com/pagarme/superbowleto) resolve o problema do registro.

**Comment by d3roch4** [comment]
Mano, vc tem um tutorial desse  superbowleto?

**Comment by otaviopace** [comment]
Olá @d3roch4, temos uma documentação no arquivo `README.md` do projeto: https://github.com/pagarme/superbowleto
