### ISSUE TITLE
Este projeto ainda está sendo mantido?

### ISSUE THREAD

**Issue by rafakato** [pagarme/node-boleto#5]
Olá, gostaria de saber se o projeto ainda está sendo mantido, pois tem dois PRs abertos há mais de um ano e nem sequer passou por review de algum dos maintainers...

**Comment by gustvao** [comment]
@rafakato faz um FORK e vamos começar a manter o seu fork.

eu vou adicionar a CAIXA em breve

**Comment by rafakato** [comment]
Beleza, já tenho um fork com a intergração do Itaú: https://github.com/rafakato/node-boleto

**Comment by chrisenytc** [comment]
Olá, Tudo bem? O projeto ainda é mantido. Estivemos a bastante ocupados ultimamente mas agora vamos voltar aos esforços de gerenciar nossos projetos open-source. Eu vou ser o responsável por gerenciar a parte open-source e a partir desse ano vamos desenvolver algumas coisas para padronizar e tornar eles fáceis de serem mantidos.

**Comment by danilomiranda** [comment]
Legal @chrisenytc.
Mas até agora os PRs continuam sem review.

**Comment by theiostream** [comment]
O projeto ser ou não mantido não é um issue. Quanto aos PRs e a eventualmente trazer contribuições feitas a forks de volta a esse repositório, vou tentar tratar disso separadamente.

**Comment by botura** [comment]
2022 e o projeto ainda é bem popular, mais de 2000 downloads por semana.

Tem alguém mantendo o projeto, ou sabem de algum fork mais atualizado?

Fiz um fork para atualizar as versões das depenências e deixar o fator de vencimento preparado para quando ele chegar em 10000 (22/02/2025). Mas seria legal manter tudo aqui no repo original.
