### ISSUE TITLE
Novos parametros: Espécie Doc. e Aceite

### ISSUE THREAD

**Issue by wakkoedu** [pagarme/node-boleto#7]
Olá,

Antes de fazer um pr, gostaria de confirmar e sugerir uma melhoria.

Existem dois campos (puramente visuais) que estão fixos no "layout.ejs", que são "Espécie Doc." (com o valor fixo "DM") e "Aceite" (com valor fixo "N").

Estou criando dois novos paramêtros opcionais na criação do objeto "boleto", e que se não informados serão preenchidos com os valores fixos atuais.

Me informem se posso mardar um pr sobre isso.

Abraços a todos!

**Comment by waltergms** [comment]
Eduardo, sabe me responder se o modulo gera o nosso número (só preciso passar o unique id do documento) ou preciso fazer toda aquela conta com o mod 11 para calcular o nosso número?

**Comment by wakkoedu** [comment]
Pelos testes e uso que fazemos aqui basta você passar um numero unico. Quem irá fazer essa validação de se o número é duplicado ou não, será no banco. Existe um método interno no node-boleto que faz o calculo para gerar o código do boleto correto (com mod 11 etc)

No boleto em si, muito das informações são puramente para exibição, isto é, não tem uma validação se estão em conflito, ou se determinada carteira não pode realizar um tipo de instrução especifica. 

Geralmente o que acontece, é que além de gerar o boleto você vai querer criar (no final do dia por exemplo), um arquivo de remessa para enviar ao banco contento uma lista de todos os boletos que foram gerados em ordem do banco ter ciência que esses boletos foram gerados. Ai nesse caso, o banco ao processar esses arquivos na virada da noite faz  validação dessas informações e retorna o resultado no dia seguinte por um arquivo de retorno.

**Comment by waltergms** [comment]
Blz Eduardo, vou fazer mais testes aqui pra ver se consigo gerar um boleto válido, você conseguiu gerar boletos válidos para o bradesco?

**Comment by wakkoedu** [comment]
Sim, consegui gerar boletos para bradesco, itau e banco do brasil atpe o momento. Para o santander e daycoval não testei.  :)

**Comment by waltergms** [comment]
Eu devo estar fazendo alguma coisa errado então porque de acordo com o manual do bradesco, quando a carteira é 09 e o documento tem id 00000000002 o digito verificador do nosso número deveria ser 8 e o meu sempre dá 7.... Se possível quando você puder, tente gerar um teste com esses números para ver se o digito verificador vai ser 8 ou 7.

**Comment by waltergms** [comment]
Olhei esse manual aqui, na página 20, aliás o código da carteira do exemplo é 19 e não 09...
http://www.bradesco.com.br/portal/PDF/pessoajuridica/solucoes-integradas/outros/layout-de-arquivo/cobranca/4008-524-0121-08-layout-cobranca-versao-portugues.pdf

**Comment by LeandroFavero** [comment]
Também preciso mudar de DM para DS. Acho válido criar um pr, até pq eu ia fazer o mesmo
 :-)

**Comment by LeandroFavero** [comment]
@waltergms pelo manual e pelo departamento de homologação, realmente precisa adicionar a carteira antes do numero para calculo do DV. E o fonte não faz isso. Não sei como @wakkoedu conseguiu. @wakkoedu  se puder nos ajudar e dizer como vc fez o calculo do DV no nosso_numero?

**Comment by theiostream** [comment]
Vou fechar esse issue e direcionar a discussão sobre o assunto para o PR aberto.
